import * as THREE from 'three';
import { MessageBus } from '@cybernoetica/core';
import type { AudioFeatures, BusMessage, Unsubscribe } from '@cybernoetica/core';
import { EMASmoothing } from '../../smoothing.js';
import type { Visualizer, VisualizerMetadata } from '../types.js';
import { registerVisualizer } from '../registry.js';

/**
 * Ferrofluid — raymarched magnetic fluid with Rosensweig instability.
 *
 * Renders a metallic blob deformed by magnetic-field-like spikes using
 * signed distance field (SDF) raymarching. The base shape is a sphere
 * displaced by audio-reactive radial spikes, inspired by the normal-field
 * instability (Rosensweig instability) of real ferrofluids under magnetic
 * fields.
 *
 * Spikes are generated by summing sharp radial cosine lobes distributed
 * over the sphere surface (icosahedrally + noise-perturbed). The metallic
 * appearance uses Fresnel reflections with an iridescent thin-film effect.
 *
 * Audio mapping:
 *   bass      -> spike amplitude (field strength)
 *   mid       -> rotation speed
 *   high      -> iridescence / color shimmer
 *   rms       -> overall scale / breathing
 *   beat      -> spike burst (sudden spike extension)
 *   centroid  -> color hue shift
 */

const ferrofluidMetadata: VisualizerMetadata = {
  type: 'ferrofluid',
  label: 'Ferrofluid',
  description: 'Magnetic fluid with Rosensweig spike instability',
  usesPerspective: true,
  params: [
    { key: 'spikeAmplitude', label: 'Spike Height', min: 0.1, max: 1.5, step: 0.05, initial: 0.5, category: 'appearance', description: 'Magnetic spike prominence' },
    { key: 'spikeCount', label: 'Spike Density', min: 3.0, max: 12.0, step: 1.0, initial: 7.0, category: 'appearance', description: 'Number of spike lobes' },
    { key: 'rotationSpeed', label: 'Rotation', min: 0.0, max: 1.0, step: 0.05, initial: 0.2, category: 'appearance', description: 'Auto-rotation speed' },
    { key: 'iridescence', label: 'Iridescence', min: 0.0, max: 1.0, step: 0.05, initial: 0.6, category: 'appearance', description: 'Thin-film color effect' },
    { key: 'metallic', label: 'Metallic', min: 0.0, max: 1.0, step: 0.05, initial: 0.85, category: 'appearance', description: 'Metallic reflectance' },
    { key: 'envBrightness', label: 'Environment', min: 0.3, max: 2.0, step: 0.1, initial: 1.0, category: 'appearance', description: 'Environment light intensity' },
    { key: 'bassToSpikes', label: 'Bass → Spikes', min: 0.0, max: 2.0, step: 0.1, initial: 1.0, category: 'audio-mapping', description: 'Bass drives spike height' },
    { key: 'midToRotation', label: 'Mid → Rotation', min: 0.0, max: 2.0, step: 0.1, initial: 1.0, category: 'audio-mapping', description: 'Mids drive rotation' },
    { key: 'highToIridescence', label: 'High → Shimmer', min: 0.0, max: 2.0, step: 0.1, initial: 1.0, category: 'audio-mapping', description: 'Highs intensify iridescence' },
    { key: 'rmsToScale', label: 'RMS → Breathe', min: 0.0, max: 2.0, step: 0.1, initial: 1.0, category: 'audio-mapping', description: 'Volume breathes the blob' },
    { key: 'beatToBurst', label: 'Beat → Burst', min: 0.0, max: 2.0, step: 0.1, initial: 1.0, category: 'audio-mapping', description: 'Beats extend spikes' },
    { key: 'centroidToHue', label: 'Centroid → Hue', min: 0.0, max: 2.0, step: 0.1, initial: 0.8, category: 'audio-mapping', description: 'Spectral centroid shifts hue' },
  ],
  viewport: { pan: false, zoom: true, orbit: true },
  viewStateFields: [
    { key: 'orbitAngle', label: 'Orbit Angle', min: -Math.PI, max: Math.PI, step: 0.02 },
    { key: 'elevation', label: 'Elevation', min: -1.2, max: 1.2, step: 0.02 },
    { key: 'distance', label: 'Distance', min: 2.0, max: 8.0, step: 0.1 },
  ],
};

export class FerrofluidVisualizer implements Visualizer {
  readonly metadata = ferrofluidMetadata;

  private unsub: Unsubscribe;
  private latestFeatures: AudioFeatures | null = null;
  private time = 0;

  private userParams: Record<string, number> = {
    spikeAmplitude: 0.5,
    spikeCount: 7.0,
    rotationSpeed: 0.2,
    iridescence: 0.6,
    metallic: 0.85,
    envBrightness: 1.0,
    bassToSpikes: 1.0,
    midToRotation: 1.0,
    highToIridescence: 1.0,
    rmsToScale: 1.0,
    beatToBurst: 1.0,
    centroidToHue: 0.8,
  };

  private _orbitAngle = 0.0;
  private _elevation = 0.3;
  private _distance = 4.5;
  private viewOverrides: Record<string, boolean> = {};

  private smoothers = {
    bass: new EMASmoothing(0.12),
    mid: new EMASmoothing(0.18),
    high: new EMASmoothing(0.22),
    rms: new EMASmoothing(0.15),
    spectralCentroid: new EMASmoothing(0.1),
    beatPulse: new EMASmoothing(0.3),
  };

  private beatBurst = new EMASmoothing(0.08);
  private material: THREE.ShaderMaterial | null = null;
  private mesh: THREE.Mesh | null = null;

  constructor(private bus: MessageBus) {
    this.unsub = bus.subscribe('audio:features', (msg: BusMessage<AudioFeatures>) => {
      this.latestFeatures = msg.payload;
    });
    this.smoothers.bass.reset(0);
    this.smoothers.mid.reset(0);
    this.smoothers.high.reset(0);
    this.smoothers.rms.reset(0.1);
    this.smoothers.spectralCentroid.reset(0.5);
    this.smoothers.beatPulse.reset(0);
    this.beatBurst.reset(0);
  }

  attach(scene: THREE.Scene): void {
    this.material = new THREE.ShaderMaterial({
      vertexShader: VERTEX_SHADER,
      fragmentShader: FRAGMENT_SHADER,
      uniforms: {
        u_time: { value: 0.0 },
        u_resolution: { value: new THREE.Vector2(1920, 1080) },
        u_orbitAngle: { value: 0.0 },
        u_elevation: { value: 0.3 },
        u_distance: { value: 4.5 },
        u_spikeAmplitude: { value: 0.5 },
        u_spikeCount: { value: 7.0 },
        u_rotationSpeed: { value: 0.2 },
        u_iridescence: { value: 0.6 },
        u_metallic: { value: 0.85 },
        u_envBrightness: { value: 1.0 },
        u_bass: { value: 0.0 },
        u_mid: { value: 0.0 },
        u_high: { value: 0.0 },
        u_rms: { value: 0.1 },
        u_spectralCentroid: { value: 0.5 },
        u_beatBurst: { value: 0.0 },
        u_hueShift: { value: 0.0 },
      },
      transparent: true,
    });

    const geometry = new THREE.PlaneGeometry(2, 2);
    this.mesh = new THREE.Mesh(geometry, this.material);
    scene.add(this.mesh);
  }

  tick(): void {
    this.time += 1 / 60;

    if (this.latestFeatures) {
      const f = this.latestFeatures;
      this.smoothers.bass.update(f.bass);
      this.smoothers.mid.update(f.mid);
      this.smoothers.high.update(f.high);
      this.smoothers.rms.update(f.rms);
      this.smoothers.spectralCentroid.update(f.spectralCentroid);
      this.smoothers.beatPulse.update(f.beatOnset ? 1.0 : 0.0);
      if (f.beatOnset && this.userParams.beatToBurst > 0) {
        this.beatBurst.reset(1.0);
      }
    } else {
      this.smoothers.beatPulse.update(0.0);
    }
    this.beatBurst.update(0.0);

    if (this.material) {
      const u = this.material.uniforms;
      const bass = this.smoothers.bass.value;
      const mid = this.smoothers.mid.value;

      u.u_time.value = this.time;
      u.u_orbitAngle.value = this._orbitAngle;
      u.u_elevation.value = this._elevation;
      u.u_distance.value = this._distance;
      u.u_spikeAmplitude.value = this.userParams.spikeAmplitude
        + bass * 0.4 * this.userParams.bassToSpikes
        + this.beatBurst.value * 0.3 * this.userParams.beatToBurst;
      u.u_spikeCount.value = this.userParams.spikeCount;
      u.u_rotationSpeed.value = this.userParams.rotationSpeed
        + mid * 0.15 * this.userParams.midToRotation;
      u.u_iridescence.value = this.userParams.iridescence
        + this.smoothers.high.value * 0.3 * this.userParams.highToIridescence;
      u.u_metallic.value = this.userParams.metallic;
      u.u_envBrightness.value = this.userParams.envBrightness;
      u.u_bass.value = bass;
      u.u_mid.value = mid;
      u.u_high.value = this.smoothers.high.value;
      u.u_rms.value = this.smoothers.rms.value * this.userParams.rmsToScale;
      u.u_spectralCentroid.value = this.smoothers.spectralCentroid.value;
      u.u_beatBurst.value = this.beatBurst.value * this.userParams.beatToBurst;
      u.u_hueShift.value = this.smoothers.spectralCentroid.value * 0.3 * this.userParams.centroidToHue;
    }
  }

  setResolution(width: number, height: number): void {
    if (this.material) this.material.uniforms.u_resolution.value.set(width, height);
  }

  setUserParam(key: string, value: number): void {
    if (key in this.userParams) this.userParams[key] = value;
  }

  getViewState(): Record<string, number> {
    return {
      orbitAngle: this._orbitAngle,
      elevation: this._elevation,
      distance: this._distance,
    };
  }

  setViewState(partial: Record<string, number>): void {
    if ('orbitAngle' in partial) {
      this._orbitAngle = partial.orbitAngle;
      this.viewOverrides.orbit = true;
    }
    if ('elevation' in partial) {
      this._elevation = Math.max(-1.2, Math.min(1.2, partial.elevation));
      this.viewOverrides.elevation = true;
    }
    if ('distance' in partial) {
      this._distance = Math.max(2.0, Math.min(8.0, partial.distance));
      this.viewOverrides.distance = true;
    }
  }

  dispose(): void {
    this.unsub();
    this.material?.dispose();
    this.mesh?.geometry.dispose();
  }
}

registerVisualizer({
  metadata: ferrofluidMetadata,
  create: (bus) => new FerrofluidVisualizer(bus),
});

const VERTEX_SHADER = /* glsl */ `
  varying vec2 vUv;
  void main() {
    vUv = uv;
    gl_Position = vec4(position, 1.0);
  }
`;

const FRAGMENT_SHADER = /* glsl */ `
  precision highp float;

  #define PI 3.14159265359
  #define TAU 6.28318530718
  #define MAX_STEPS 80
  #define MAX_DIST 12.0
  #define SURF_DIST 0.002

  uniform float u_time;
  uniform vec2 u_resolution;
  uniform float u_orbitAngle;
  uniform float u_elevation;
  uniform float u_distance;
  uniform float u_spikeAmplitude;
  uniform float u_spikeCount;
  uniform float u_rotationSpeed;
  uniform float u_iridescence;
  uniform float u_metallic;
  uniform float u_envBrightness;
  uniform float u_bass;
  uniform float u_mid;
  uniform float u_high;
  uniform float u_rms;
  uniform float u_spectralCentroid;
  uniform float u_beatBurst;
  uniform float u_hueShift;

  varying vec2 vUv;

  mat2 rot2(float a) {
    float c = cos(a), s = sin(a);
    return mat2(c, -s, s, c);
  }

  // Smooth noise for organic deformation
  float hash3(vec3 p) {
    p = fract(p * vec3(443.897, 441.423, 437.195));
    p += dot(p, p.yzx + 19.19);
    return fract((p.x + p.y) * p.z);
  }

  float noise3(vec3 p) {
    vec3 i = floor(p);
    vec3 f = fract(p);
    f = f * f * (3.0 - 2.0 * f);

    return mix(
      mix(mix(hash3(i), hash3(i + vec3(1, 0, 0)), f.x),
          mix(hash3(i + vec3(0, 1, 0)), hash3(i + vec3(1, 1, 0)), f.x), f.y),
      mix(mix(hash3(i + vec3(0, 0, 1)), hash3(i + vec3(1, 0, 1)), f.x),
          mix(hash3(i + vec3(0, 1, 1)), hash3(i + vec3(1, 1, 1)), f.x), f.y),
      f.z
    );
  }

  // Spike displacement: sharp radial protrusions like Rosensweig instability
  float spikeDisplacement(vec3 p, float t) {
    vec3 n = normalize(p);

    // Animate rotation of spike field
    float rotAngle = t * u_rotationSpeed;
    n.xz *= rot2(rotAngle);
    n.yz *= rot2(rotAngle * 0.7);

    // Spherical harmonics-like spike pattern
    float count = u_spikeCount;
    float spikes = 0.0;

    // Latitude-longitude based spike pattern
    float theta = acos(clamp(n.y, -1.0, 1.0));
    float phi = atan(n.z, n.x);

    // Multiple spike rings at different latitudes
    float latSpikes = pow(max(0.0, cos(theta * count * 0.5)), 4.0);
    float lonSpikes = pow(max(0.0, cos(phi * count)), 4.0);

    // Combine: spikes form at intersections of lat/lon maxima
    spikes = latSpikes * 0.5 + lonSpikes * 0.3;

    // Add organic noise modulation so spikes aren't perfectly regular
    float noiseVal = noise3(n * 3.0 + vec3(t * 0.3));
    spikes += pow(noiseVal, 2.0) * 0.4;

    // Sharp spike tips: apply a power curve
    spikes = pow(max(0.0, spikes), 1.5);

    return spikes * u_spikeAmplitude;
  }

  // SDF for the ferrofluid blob
  float sdFerrofluid(vec3 p, float t) {
    float r = length(p);
    float baseRadius = 1.0 + u_rms * 0.15;

    // Spike displacement
    float spikes = spikeDisplacement(p, t);

    // Low-frequency organic breathing
    float breathe = sin(t * 1.2) * 0.03 * (1.0 + u_bass * 0.5);

    // SDF: sphere minus displacement
    return r - baseRadius - spikes - breathe;
  }

  // Normal estimation
  vec3 getNormal(vec3 p, float t) {
    float eps = 0.003;
    float d = sdFerrofluid(p, t);
    return normalize(vec3(
      sdFerrofluid(p + vec3(eps, 0, 0), t) - d,
      sdFerrofluid(p + vec3(0, eps, 0), t) - d,
      sdFerrofluid(p + vec3(0, 0, eps), t) - d
    ));
  }

  // Thin-film iridescence: wavelength-dependent interference
  vec3 thinFilmIridescence(float cosTheta, float thickness) {
    float delta = thickness * cosTheta * 2.0;
    vec3 wavelengths = vec3(650.0, 510.0, 475.0); // RGB wavelengths in nm
    vec3 phase = TAU * delta / (wavelengths * 0.001);
    return 0.5 + 0.5 * cos(phase);
  }

  // Environment: simple gradient + fake reflections
  vec3 envColor(vec3 dir) {
    float y = dir.y * 0.5 + 0.5;
    vec3 sky = mix(vec3(0.05, 0.05, 0.15), vec3(0.15, 0.12, 0.25), y);
    // Bright spot (key light reflection)
    float sun = pow(max(0.0, dot(dir, normalize(vec3(1.0, 1.0, 0.5)))), 32.0);
    sky += vec3(1.0, 0.9, 0.7) * sun * 2.0;
    // Rim light
    float rim = pow(max(0.0, dot(dir, normalize(vec3(-0.5, 0.3, -1.0)))), 16.0);
    sky += vec3(0.3, 0.5, 1.0) * rim * 0.8;
    return sky * u_envBrightness;
  }

  vec3 hsv2rgb(vec3 c) {
    vec4 K = vec4(1.0, 2.0/3.0, 1.0/3.0, 3.0);
    vec3 p = abs(fract(c.xxx + K.xyz) * 6.0 - K.www);
    return c.z * mix(K.xxx, clamp(p - K.xxx, 0.0, 1.0), c.y);
  }

  void main() {
    vec2 uv = (gl_FragCoord.xy - 0.5 * u_resolution) / min(u_resolution.x, u_resolution.y);

    // Camera setup from orbit parameters
    float camAngle = u_orbitAngle;
    float camElev = u_elevation;
    float camDist = u_distance;

    vec3 camPos = vec3(
      sin(camAngle) * cos(camElev) * camDist,
      sin(camElev) * camDist,
      cos(camAngle) * cos(camElev) * camDist
    );

    vec3 target = vec3(0.0);
    vec3 forward = normalize(target - camPos);
    vec3 right = normalize(cross(forward, vec3(0.0, 1.0, 0.0)));
    vec3 up = cross(right, forward);

    vec3 rd = normalize(forward * 1.8 + right * uv.x + up * uv.y);

    float t = u_time;

    // Raymarch
    float totalDist = 0.0;
    float dist;
    vec3 p;
    bool hit = false;

    for (int i = 0; i < MAX_STEPS; i++) {
      p = camPos + rd * totalDist;
      dist = sdFerrofluid(p, t);
      if (dist < SURF_DIST) {
        hit = true;
        break;
      }
      if (totalDist > MAX_DIST) break;
      totalDist += dist * 0.8; // Slightly conservative step for stability
    }

    vec3 color;

    if (hit) {
      vec3 normal = getNormal(p, t);
      vec3 viewDir = normalize(camPos - p);

      // Fresnel
      float NdotV = max(0.0, dot(normal, viewDir));
      float fresnel = pow(1.0 - NdotV, 5.0);
      fresnel = mix(0.04, 1.0, fresnel);

      // Reflection
      vec3 refl = reflect(-viewDir, normal);
      vec3 reflColor = envColor(refl);

      // Base metallic color: dark iron with hue shift
      float hue = 0.6 + u_hueShift;
      vec3 baseColor = hsv2rgb(vec3(hue, 0.15, 0.08));

      // Lighting
      vec3 lightDir = normalize(vec3(1.0, 1.5, 0.8));
      float diff = max(0.0, dot(normal, lightDir)) * 0.5 + 0.5;
      vec3 halfVec = normalize(lightDir + viewDir);
      float spec = pow(max(0.0, dot(normal, halfVec)), 64.0);

      // Iridescence on the surface
      float filmThickness = 400.0 + noise3(p * 5.0 + t * 0.5) * 200.0;
      filmThickness += u_spectralCentroid * 100.0;
      vec3 iridColor = thinFilmIridescence(NdotV, filmThickness);

      // Compose
      vec3 diffuse = baseColor * diff * u_envBrightness;
      vec3 specular = vec3(spec) * u_envBrightness;
      vec3 reflection = reflColor * fresnel * u_metallic;

      color = diffuse * (1.0 - u_metallic * 0.5);
      color += reflection;
      color += specular * 0.8;

      // Apply iridescence
      color = mix(color, color * iridColor * 2.0, u_iridescence);

      // Edge glow on spikes
      float edgeGlow = pow(1.0 - NdotV, 3.0);
      vec3 glowColor = hsv2rgb(vec3(hue + 0.15, 0.6, 1.0));
      color += glowColor * edgeGlow * 0.3 * (1.0 + u_beatBurst);

      // AO approximation: deeper crevices between spikes are darker
      float ao = 0.5 + 0.5 * NdotV;
      color *= ao;
    } else {
      // Background: dark with subtle radial gradient
      float bgGrad = length(uv) * 0.5;
      color = mix(vec3(0.02, 0.02, 0.05), vec3(0.005, 0.005, 0.015), bgGrad);

      // Subtle ambient glow around the blob
      float glowDist = totalDist - camDist + 1.5;
      float glow = exp(-glowDist * glowDist * 0.5) * 0.1;
      color += vec3(0.1, 0.15, 0.3) * glow * (1.0 + u_rms);
    }

    // Vignette
    float aspect = u_resolution.x / u_resolution.y;
    vec2 screenUv = gl_FragCoord.xy / u_resolution;
    float vignette = 1.0 - 0.3 * length((screenUv - 0.5) * vec2(aspect, 1.0));
    color *= vignette;

    // Tone mapping
    color = color / (1.0 + color);

    // Slight gamma for richness
    color = pow(color, vec3(0.95));

    gl_FragColor = vec4(color, 1.0);
  }
`;
