import type { VisualizerDocumentation, VisualizerReference } from './types.js';

function ref(label: string, url: string): VisualizerReference {
  return { label, url };
}

const AUDIO_BANDS = ['bands', 'rms', 'spectral-centroid', 'beat'] as const;
const AUDIO_BANDS_AND_FLUX = ['bands', 'rms', 'spectral-centroid', 'spectral-flux', 'beat'] as const;
const AUDIO_WAVEFORM = ['fft', 'bands', 'rms', 'spectral-centroid', 'beat'] as const;

export const VISUALIZER_DOCUMENTATION: Record<string, VisualizerDocumentation> = {
  orbital: {
    summary: 'CPU particle simulation with orbiting emitters, central gravity, and curl-like turbulence.',
    math: 'No single closed-form reference; the system combines emitter orbits, inverse-square pull, damping, and procedural turbulence.',
    references: [
      ref('Inverse Square Law', 'https://scienceworld.wolfram.com/physics/InverseSquareLaw.html'),
    ],
    audioInputsUsed: [...AUDIO_BANDS, 'spectral-flux'],
    requiresFFT: false,
    perfTier: 'high',
    mobileSafe: false,
  },
  'orbital-beta': {
    summary: 'Chaotic 3D particle simulation with tilted emitters and fully 3D tangential launch vectors.',
    math: 'No single closed-form reference; this variant extends the orbital particle system with 3D emitter frames and drift perturbations.',
    references: [
      ref('Inverse Square Law', 'https://scienceworld.wolfram.com/physics/InverseSquareLaw.html'),
    ],
    audioInputsUsed: [...AUDIO_BANDS, 'spectral-flux'],
    requiresFFT: false,
    perfTier: 'high',
    mobileSafe: false,
  },
  'orbital-gamma': {
    summary: 'Interactive particle sculpting system with user-placed attractors and repulsors.',
    math: 'No single closed-form reference; this variant builds on the orbital particle system and adds temporary inverse-square force fields.',
    references: [
      ref('Inverse Square Law', 'https://scienceworld.wolfram.com/physics/InverseSquareLaw.html'),
    ],
    audioInputsUsed: [...AUDIO_BANDS, 'spectral-flux'],
    requiresFFT: false,
    perfTier: 'high',
    mobileSafe: false,
  },
  waveform: {
    summary: 'Layered FFT-driven waveform renderer with procedural idle motion and spectral color mapping.',
    math: 'Combines sampled FFT magnitudes with synthetic line layers and glow falloff.',
    references: [
      ref('Fourier Transform', 'https://mathworld.wolfram.com/FourierTransform.html'),
      ref('Nyquist Frequency', 'https://mathworld.wolfram.com/NyquistFrequency.html'),
    ],
    audioInputsUsed: [...AUDIO_WAVEFORM],
    requiresFFT: true,
    perfTier: 'medium',
    mobileSafe: true,
  },
  mandelbrot: {
    summary: 'Quadratic escape-time fractal with smooth iteration coloring and zoom cycling.',
    math: 'z_(n+1) = z_n^2 + c, with c sampled from the complex plane and z_0 = 0.',
    references: [ref('Mandelbrot Set', 'https://mathworld.wolfram.com/MandelbrotSet.html')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'medium',
    mobileSafe: true,
  },
  burningship: {
    summary: 'Absolute-value escape-time fractal derived from the Mandelbrot recurrence.',
    math: 'z_(n+1) = (|Re(z_n)| + i|Im(z_n)|)^2 + c, with z_0 = 0.',
    references: [
      ref('Burning Ship Fractal', 'https://www.paulbourke.net/fractals/burnship/'),
      ref('Burning Ship Fractal (overview)', 'https://en.wikipedia.org/wiki/Burning_Ship_fractal'),
    ],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'medium',
    mobileSafe: true,
  },
  julia: {
    summary: 'Quadratic Julia-set renderer that animates the complex seed parameter c.',
    math: 'z_(n+1) = z_n^2 + c for a fixed complex seed c; the set is the boundary of points that remain bounded.',
    references: [ref('Julia Set', 'https://mathworld.wolfram.com/JuliaSet.html')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'medium',
    mobileSafe: true,
  },
  newton: {
    summary: 'Newton-Raphson basin renderer for polynomial root finding.',
    math: 'z_(n+1) = z_n - f(z_n) / f\'(z_n), colored by converged root and convergence speed.',
    references: [ref('Newton-Raphson Fractal', 'https://mathworld.wolfram.com/Newton-RaphsonFractal.html')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'medium',
    mobileSafe: true,
  },
  lyapunov: {
    summary: 'Lyapunov-exponent field visualizing chaotic and stable regions of parameter space.',
    math: 'Evaluates the Lyapunov exponent over an iterated logistic-map parameter sequence.',
    references: [ref('Lyapunov Exponent', 'https://mathworld.wolfram.com/LyapunovExponent.html')],
    audioInputsUsed: [...AUDIO_BANDS_AND_FLUX],
    requiresFFT: false,
    perfTier: 'medium',
    mobileSafe: false,
  },
  apollonian: {
    summary: 'Recursive circle-packing visualizer inspired by Apollonian gaskets.',
    math: 'Constructs mutually tangent circle packings related to Soddy circles and Apollonian gaskets.',
    references: [ref('Apollonian Gasket', 'https://mathworld.wolfram.com/ApollonianGasket.html')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'medium',
    mobileSafe: true,
  },
  quatjulia: {
    summary: 'Quaternion Julia fractal rendered as a 3D distance-estimated form.',
    math: 'Extends the Julia recurrence to quaternions and raymarches the resulting 3D set.',
    references: [ref('Quaternion Julia Sets', 'https://en.wikipedia.org/wiki/Quaternion_Julia_set')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'extreme',
    mobileSafe: false,
  },
  voronoi: {
    summary: 'Distance-field Voronoi renderer with animated seeds and metric blending.',
    math: 'Partitions the plane by nearest seed point using F1/F2 cell distances, with Euclidean-Manhattan interpolation.',
    references: [ref('Voronoi Diagram', 'https://mathworld.wolfram.com/VoronoiDiagram.html')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'medium',
    mobileSafe: true,
  },
  lissajous: {
    summary: 'Damped harmonograph / Lissajous hybrid rendered as luminous curve trails.',
    math: 'Pure Lissajous figures follow x = A cos(ω_x t - δ_x), y = B cos(ω_y t - δ_y); this visualizer adds harmonograph-style damping and extra harmonics.',
    references: [
      ref('Lissajous Curve', 'https://mathworld.wolfram.com/LissajousCurve.html'),
      ref('Harmonograph', 'https://mathworld.wolfram.com/Harmonograph.html'),
    ],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'medium',
    mobileSafe: true,
  },
  kaleidoscope: {
    summary: 'Radial fold-and-mirror pattern generator based on dihedral symmetry.',
    math: 'Maps points into a reflected angular wedge of size 2π / n, corresponding to dihedral-group symmetry.',
    references: [
      ref('Dihedral Group', 'https://mathworld.wolfram.com/DihedralGroup.html'),
      ref('Symmetry Group', 'https://mathworld.wolfram.com/SymmetryGroup.html'),
    ],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'medium',
    mobileSafe: true,
  },
  hyperbolic: {
    summary: 'Hyperbolic tiling visualizer in a Poincare-disk-style model.',
    math: 'Uses hyperbolic geometry in the disk model to tile beyond Euclidean angle limits.',
    references: [ref('Poincare Hyperbolic Disk', 'https://mathworld.wolfram.com/PoincareHyperbolicDisk.html')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'high',
    mobileSafe: false,
  },
  chladni: {
    summary: 'Rectangular Chladni plate node pattern renderer.',
    math: 'Uses modal nodal-line patterns from vibrating plates, typically from sin/cos mode combinations.',
    references: [ref('Chladni Figure', 'https://en.wikipedia.org/wiki/Chladni_figure')],
    audioInputsUsed: [...AUDIO_BANDS, 'spectral-flux'],
    requiresFFT: false,
    perfTier: 'medium',
    mobileSafe: true,
  },
  'chladni-circular': {
    summary: 'Circular-membrane cymatic pattern renderer.',
    math: 'Uses circular membrane vibration modes related to Bessel-function nodal patterns.',
    references: [ref('Bessel Function', 'https://mathworld.wolfram.com/BesselFunctionoftheFirstKind.html')],
    audioInputsUsed: [...AUDIO_BANDS, 'spectral-flux'],
    requiresFFT: false,
    perfTier: 'medium',
    mobileSafe: true,
  },
  phyllotaxis: {
    summary: 'Golden-angle spiral growth visualizer inspired by sunflower packing.',
    math: 'Typically places point n at radius proportional to sqrt(n) and angle n times the golden angle.',
    references: [ref('Phyllotaxis', 'https://mathworld.wolfram.com/Phyllotaxis.html')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'low',
    mobileSafe: true,
  },
  superformula: {
    summary: 'Radial shape visualizer based on the Gielis superformula.',
    math: 'Generalizes superellipses with a polar radius formula controlled by m, n1, n2, and n3.',
    references: [ref('Superformula', 'https://mathworld.wolfram.com/Superformula.html')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'medium',
    mobileSafe: true,
  },
  quasicrystal: {
    summary: 'Aperiodic interference visualizer inspired by quasicrystal symmetry.',
    math: 'Builds aperiodic order from interference sums with forbidden crystallographic symmetries such as 5-fold order.',
    references: [ref('Crystallography Restriction', 'https://mathworld.wolfram.com/CrystallographyRestriction.html')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'medium',
    mobileSafe: true,
  },
  domainwarp: {
    summary: 'Noise-field visualizer that warps coordinates before resampling a base field.',
    math: 'Domain warping composes p with a secondary noise offset field before evaluating the main function.',
    references: [ref('Fractal Brownian Motion', 'https://thebookofshaders.com/13/')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'high',
    mobileSafe: false,
  },
  'domainwarp-recursive': {
    summary: 'Recursive domain-warp visualizer with repeated coordinate remapping.',
    math: 'Applies multiple nested warp stages to increase deformation complexity.',
    references: [ref('Fractal Brownian Motion', 'https://thebookofshaders.com/13/')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'high',
    mobileSafe: false,
  },
  truchet: {
    summary: 'Tile-based pattern visualizer using Truchet-style local motifs.',
    math: 'Uses a repeated square tiling with per-cell motif selection and symmetry transforms.',
    references: [ref('Truchet Tiling', 'https://en.wikipedia.org/wiki/Truchet_tiles')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'low',
    mobileSafe: true,
  },
  clifford: {
    summary: 'Clifford attractor renderer for planar strange-attractor point sets.',
    math: 'Iterates the standard Clifford attractor recurrence on x and y.',
    references: [ref('Clifford Attractor', 'https://en.wikipedia.org/wiki/Clifford_attractor')],
    audioInputsUsed: [...AUDIO_BANDS_AND_FLUX],
    requiresFFT: false,
    perfTier: 'medium',
    mobileSafe: true,
  },
  harmonograph: {
    summary: 'Damped pendulum-trace visualizer in the style of mechanical harmonographs.',
    math: 'Models orthogonal damped sinusoids whose traces contract as energy decays.',
    references: [ref('Harmonograph', 'https://mathworld.wolfram.com/Harmonograph.html')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'low',
    mobileSafe: true,
  },
  moire: {
    summary: 'Interference renderer from overlapping line or grid fields.',
    math: 'Produces moire patterns by superposing nearly aligned periodic structures.',
    references: [ref('Moire Pattern', 'https://en.wikipedia.org/wiki/Moir%C3%A9_pattern')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'low',
    mobileSafe: true,
  },
  plasma: {
    summary: 'Classic demoscene plasma shader from summed smooth waves and palette mapping.',
    math: 'Combines low-frequency sinusoidal fields and color palettes to produce a continuous plasma field.',
    references: [ref('Plasma Effect', 'https://en.wikipedia.org/wiki/Plasma_effect')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'low',
    mobileSafe: true,
  },
  flowfield: {
    summary: 'Vector-field streamline visualizer.',
    math: 'Samples a procedurally defined 2D vector field and advects streamlines or particles through it.',
    references: [ref('Vector Field', 'https://mathworld.wolfram.com/VectorField.html')],
    audioInputsUsed: [...AUDIO_BANDS_AND_FLUX],
    requiresFFT: false,
    perfTier: 'medium',
    mobileSafe: true,
  },
  spirograph: {
    summary: 'Epitrochoid / hypotrochoid curve visualizer.',
    math: 'Uses rolling-circle parametric curves such as epitrochoids and hypotrochoids.',
    references: [ref('Spirograph', 'https://mathworld.wolfram.com/Spirograph.html')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'low',
    mobileSafe: true,
  },
  automata: {
    summary: 'Cellular automaton visualizer.',
    math: 'Evolves a discrete state grid from local update rules over time.',
    references: [ref('Cellular Automaton', 'https://mathworld.wolfram.com/CellularAutomaton.html')],
    audioInputsUsed: [...AUDIO_BANDS_AND_FLUX],
    requiresFFT: false,
    perfTier: 'medium',
    mobileSafe: true,
  },
  reaction: {
    summary: 'Gray-Scott-style reaction-diffusion pattern visualizer.',
    math: 'Approximates coupled reaction and diffusion updates that self-organize spots and stripes.',
    references: [ref('Reaction-Diffusion', 'https://mathworld.wolfram.com/Reaction-DiffusionEquation.html')],
    audioInputsUsed: [...AUDIO_BANDS_AND_FLUX],
    requiresFFT: false,
    perfTier: 'high',
    mobileSafe: false,
  },
  rosecurve: {
    summary: 'Polar rhodonea-curve renderer.',
    math: 'Uses polar curves of the form r = a cos(kθ) or r = a sin(kθ).',
    references: [ref('Rose Curve', 'https://mathworld.wolfram.com/RoseCurve.html')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'low',
    mobileSafe: true,
  },
  penrose: {
    summary: 'Aperiodic Penrose-style tiling visualizer.',
    math: 'Uses non-periodic tilings with 5-fold local symmetry and matching rules.',
    references: [ref('Penrose Tiles', 'https://mathworld.wolfram.com/PenroseTiles.html')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'high',
    mobileSafe: false,
  },
  soliton: {
    summary: 'Wave visualizer inspired by soliton interactions.',
    math: 'Uses solitary-wave style profiles that maintain shape under propagation and interaction.',
    references: [ref('Soliton', 'https://mathworld.wolfram.com/Soliton.html')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'medium',
    mobileSafe: true,
  },
  terrain: {
    summary: 'Raymarched procedural terrain.',
    math: 'Uses signed-distance terrain surfaces and layered noise / height fields under raymarching.',
    references: [ref('Terrain Modeling', 'https://en.wikipedia.org/wiki/Terrain_rendering')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'extreme',
    mobileSafe: false,
  },
  geodesic: {
    summary: 'Raymarched geodesic-dome renderer.',
    math: 'Uses geodesic or Goldberg-style sphere subdivision ideas in a distance-estimated scene.',
    references: [ref('Geodesic Dome', 'https://mathworld.wolfram.com/GeodesicDome.html')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'high',
    mobileSafe: false,
  },
  tunnel: {
    summary: 'Infinite tunnel renderer.',
    math: 'Uses repeated radial distance fields and raymarching along a longitudinal axis.',
    references: [ref('Distance Function Basics', 'https://iquilezles.org/articles/distfunctions/')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'high',
    mobileSafe: false,
  },
  interference: {
    summary: 'Wave-interference field visualizer.',
    math: 'Superposes multiple oscillatory sources to produce constructive and destructive interference.',
    references: [ref('Wave Interference', 'https://mathworld.wolfram.com/WaveInterference.html')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'medium',
    mobileSafe: true,
  },
  metaballs: {
    summary: 'Implicit-surface metaball renderer.',
    math: 'Uses scalar field summation around moving centers with an isosurface threshold.',
    references: [ref('Metaball', 'https://en.wikipedia.org/wiki/Metaballs')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'high',
    mobileSafe: false,
  },
  mandelbulb: {
    summary: '3D power-form Mandelbulb fractal raymarcher.',
    math: 'Extends Mandelbrot-style power iteration to spherical 3D coordinates and distance estimation.',
    references: [ref('Mandelbulb', 'https://en.wikipedia.org/wiki/Mandelbulb')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'extreme',
    mobileSafe: false,
  },
  attractor: {
    summary: 'Classic strange-attractor particle renderer.',
    math: 'Integrates a low-dimensional chaotic attractor in continuous or discrete time.',
    references: [ref('Strange Attractor', 'https://mathworld.wolfram.com/StrangeAttractor.html')],
    audioInputsUsed: [...AUDIO_BANDS_AND_FLUX],
    requiresFFT: false,
    perfTier: 'medium',
    mobileSafe: true,
  },
  hopalong: {
    summary: 'Hopalong attractor point renderer.',
    math: 'Uses the Martin / Hopalong attractor recurrence to generate dense planar point sets.',
    references: [ref('Hopalong Attractor', 'https://en.wikipedia.org/wiki/Hopalong_attractor')],
    audioInputsUsed: [...AUDIO_BANDS_AND_FLUX],
    requiresFFT: false,
    perfTier: 'medium',
    mobileSafe: true,
  },
  dejong: {
    summary: 'Peter de Jong attractor renderer.',
    math: 'Uses the standard de Jong map with sinusoidal coordinate recurrences.',
    references: [ref('De Jong Attractor', 'https://en.wikipedia.org/wiki/Attractor#Peter_de_Jong_map')],
    audioInputsUsed: [...AUDIO_BANDS_AND_FLUX],
    requiresFFT: false,
    perfTier: 'medium',
    mobileSafe: true,
  },
  ikeda: {
    summary: 'Ikeda-map attractor renderer.',
    math: 'Uses the Ikeda map recurrence derived from an optical resonator model.',
    references: [ref('Ikeda Map', 'https://en.wikipedia.org/wiki/Ikeda_map')],
    audioInputsUsed: [...AUDIO_BANDS_AND_FLUX],
    requiresFFT: false,
    perfTier: 'medium',
    mobileSafe: true,
  },
  aizawa: {
    summary: 'Aizawa attractor renderer.',
    math: 'Uses the six-parameter Aizawa continuous-time chaotic system.',
    references: [ref('Aizawa Attractor', 'https://en.wikipedia.org/wiki/Aizawa_attractor')],
    audioInputsUsed: [...AUDIO_BANDS_AND_FLUX],
    requiresFFT: false,
    perfTier: 'high',
    mobileSafe: false,
  },
  magnetic: {
    summary: 'Field-line visualizer for dipole / multipole magnetic patterns.',
    math: 'Uses vector-field structure inspired by magnetic dipole and multipole fields.',
    references: [ref('Magnetic Dipole', 'https://mathworld.wolfram.com/MagneticDipole.html')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'medium',
    mobileSafe: true,
  },
  gyroid: {
    summary: 'Gyroid minimal-surface renderer.',
    math: 'Uses the implicit triply periodic gyroid surface sin(x)cos(y)+sin(y)cos(z)+sin(z)cos(x)=0.',
    references: [ref('Gyroid', 'https://mathworld.wolfram.com/Gyroid.html')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'extreme',
    mobileSafe: false,
  },
  hopf: {
    summary: 'Hopf-fibration-inspired fiber bundle renderer.',
    math: 'Maps S^3 fibers to circles over points on S^2 in the Hopf fibration.',
    references: [ref('Hopf Fibration', 'https://mathworld.wolfram.com/HopfMap.html')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'extreme',
    mobileSafe: false,
  },
  kleinian: {
    summary: 'Kleinian-group limit-set visualizer inspired by Indra’s Pearls.',
    math: 'Uses iterative Möbius transformations and limit sets of Kleinian groups.',
    references: [ref('Kleinian Group', 'https://mathworld.wolfram.com/KleinianGroup.html')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'high',
    mobileSafe: false,
  },
  caustics: {
    summary: 'Refraction / caustic-pattern visualizer.',
    math: 'Approximates concentrated light patterns caused by refracting or reflecting surfaces.',
    references: [ref('Caustic', 'https://en.wikipedia.org/wiki/Caustic_(optics)')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'high',
    mobileSafe: false,
  },
  ferrofluid: {
    summary: 'Magnetic-fluid instability renderer.',
    math: 'Draws on Rosensweig-style spike instabilities under magnetic forcing.',
    references: [ref('Rosensweig Instability', 'https://en.wikipedia.org/wiki/Rosensweig_instability')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'extreme',
    mobileSafe: false,
  },
  orbittrap: {
    summary: 'Orbit-trap fractal coloring visualizer.',
    math: 'Colors escape-time fractals by measuring distance to a chosen geometric trap during iteration.',
    references: [ref('Orbit Trap', 'https://en.wikipedia.org/wiki/Orbit_trap')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'medium',
    mobileSafe: true,
  },
  aurora: {
    summary: 'Aurora curtain renderer.',
    math: 'Uses layered noise and vertical falloff to approximate curtain-like auroral motion rather than a strict physical plasma model.',
    references: [ref('Aurora', 'https://en.wikipedia.org/wiki/Aurora')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'high',
    mobileSafe: false,
  },
  dendrite: {
    summary: 'Dendritic crystal-growth visualizer.',
    math: 'Approximates branching growth processes associated with diffusion-limited or anisotropic crystal formation.',
    references: [ref('Dendrite', 'https://en.wikipedia.org/wiki/Dendrite_(crystal)')],
    audioInputsUsed: [...AUDIO_BANDS_AND_FLUX],
    requiresFFT: false,
    perfTier: 'medium',
    mobileSafe: true,
  },
  torusknot: {
    summary: 'Raymarched torus-knot visualizer.',
    math: 'Uses parameterized torus knots classified by integer winding numbers p and q.',
    references: [ref('Torus Knot', 'https://mathworld.wolfram.com/TorusKnot.html')],
    audioInputsUsed: [...AUDIO_BANDS],
    requiresFFT: false,
    perfTier: 'extreme',
    mobileSafe: false,
  },
};

export function getVisualizerDocumentation(type: string): VisualizerDocumentation | undefined {
  return VISUALIZER_DOCUMENTATION[type];
}

export function listVisualizerDocumentation(): Array<{ type: string; documentation: VisualizerDocumentation }> {
  return Object.entries(VISUALIZER_DOCUMENTATION).map(([type, documentation]) => ({ type, documentation }));
}
